# Generated by Django 5.2.5 on 2025-08-28 21:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('locations', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('admin_plaza', 'Administrator de Plaza'), ('gerente_local', 'Gerente de Local'), ('usuario_local', 'Usuario Local')], default='usuario_local', max_length=20, verbose_name='Rol')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaza_admins', to='locations.location', verbose_name='Plaza asignada')),
                ('managed_locations', models.ManyToManyField(blank=True, related_name='admins', to='locations.location', verbose_name='Ubicaciones gestionadas')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='stores.store', verbose_name='Tienda asignada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'indexes': [models.Index(fields=['role'], name='accounts_us_role_e16858_idx'), models.Index(fields=['location'], name='accounts_us_locatio_1b591f_idx'), models.Index(fields=['store'], name='accounts_us_store_i_0f33b6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('role', 'admin_plaza'), ('location__isnull', True), _negated=True), name='admin_plaza_must_have_location'), models.CheckConstraint(condition=models.Q(('role', 'gerente_local'), ('store__isnull', True), _negated=True), name='gerente_local_must_have_store'), models.CheckConstraint(condition=models.Q(('role', 'usuario_local'), ('store__isnull', True), _negated=True), name='usuario_local_must_have_store')],
            },
        ),
    ]
