# Generated by Django 5.2.5 on 2025-08-25 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('tolerance_minutes', models.PositiveIntegerField(default=15)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='locations.location')),
            ],
        ),
    ]
