# Generated by Django 5.2.5 on 2025-08-28 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('tolerance_minutes', models.PositiveIntegerField(default=15)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
