# Generated by Django 5.2.5 on 2025-08-28 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parkings', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado por validación de tienda', max_digits=10)),
                ('exit_time', models.DateTimeField(blank=True, help_text='Momento de salida del estacionamiento', null=True)),
                ('plate_number', models.CharField(blank=True, help_text='Placa del vehículo', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('validated', 'Validated'), ('paid', 'Paid'), ('exited', 'Exited'), ('expired', 'Expired'), ('lost', 'Lost'), ('canceled', 'Canceled')], default='issued', max_length=16)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='parkings.parking')),
                ('validated_by_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_tickets', to='stores.store')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parking', 'created_at'], name='tickets_tic_parking_65646f_idx'), models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'), models.Index(fields=['status', 'created_at'], name='tickets_tic_status_8acd21_idx'), models.Index(fields=['exit_time'], name='tickets_tic_exit_ti_423690_idx'), models.Index(fields=['plate_number'], name='tickets_tic_plate_n_f7226c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ticket_amount_non_negative'), models.CheckConstraint(condition=models.Q(('discount_applied__gte', 0)), name='ticket_discount_non_negative')],
            },
        ),
    ]
