# Generated by Django 5.2.5 on 2025-08-25 20:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='locations.location')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='stores_stor_name_988b60_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnitOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_occupancies', to='stores.store')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupancies', to='stores.commercialunit')),
            ],
            options={
                'ordering': ['unit', '-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='commercialunit',
            index=models.Index(fields=['location', 'code'], name='stores_comm_locatio_bf4fae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commercialunit',
            unique_together={('location', 'code')},
        ),
        migrations.AddIndex(
            model_name='unitoccupancy',
            index=models.Index(fields=['unit', 'start_date'], name='stores_unit_unit_id_b8460c_idx'),
        ),
        migrations.AddIndex(
            model_name='unitoccupancy',
            index=models.Index(fields=['unit', 'end_date'], name='stores_unit_unit_id_c425f2_idx'),
        ),
    ]
